In [1]:
import pandas as pd

In [2]:
df = pd.read_parquet('/Users/anuj/Documents/CodeBase/Bioinformatics_projects/biological-age-prediction/data/processed/dataset.parquet')

In [3]:
df

,SEQN,SDDSRVYR,RIDSTATR,RIAGENDR,RIDAGEYR,RIDAGEMN,RIDRETH1,RIDRETH3,RIDEXMON,RIDEXAGY,...,DMDYRUSZ,DMDMARTZ,WTINTPRP,WTMECPRP,LBDHRPLC,WTSAFPRP,LBXNRBC,LBDSATLC,LBDSGTLC,LBDSTBLC
0,62161.0,7.0,2.0,1.0,22.0,NaN,3.0,3.0,2.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,62162.0,7.0,2.0,2.0,3.0,NaN,1.0,1.0,1.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,62163.0,7.0,2.0,1.0,14.0,NaN,5.0,6.0,2.0,14.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,62164.0,7.0,2.0,2.0,44.0,NaN,3.0,3.0,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,62165.0,7.0,2.0,2.0,14.0,NaN,4.0,4.0,2.0,14.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45457,124818.0,66.0,2.0,1.0,40.0,NaN,4.0,4.0,1.0,NaN,...,NaN,1.0,21586.596728,21666.889837,NaN,NaN,0.1,5.397605e-79,5.397605e-79,5.397605e-79
45458,124819.0,66.0,2.0,1.0,2.0,NaN,4.0,4.0,2.0,NaN,...,NaN,NaN,1664.919253,1838.169709,NaN,NaN,NaN,NaN,NaN,NaN
45459,124820.0,66.0,2.0,2.0,7.0,NaN,3.0,3.0,2.0,NaN,...,NaN,NaN,14819.783161,16497.806674,NaN,NaN,0.1,NaN,NaN,NaN
45460,124821.0,66.0,2.0,1.0,63.0,NaN,4.0,4.0,1.0,NaN,...,NaN,2.0,4666.817952,4853.430230,NaN,10704.467871,0.1,5.397605e-79,5.397605e-79,5.397605e-79
45461,124822.0,66.0,2.0,1.0,74.0,NaN,2.0,2.0,2.0,NaN,...,4.0,1.0,14024.476634,15195.796658,NaN,36585.328133,0.2,5.397605e-79,5.397605e-79,5.397605e-79

In [4]:
df.info()
df.shape

<class 'pandas.DataFrame'>
RangeIndex: 45462 entries, 0 to 45461
Columns: 128 entries, SEQN to LBDSTBLC
dtypes: float64(127), str(1)
memory usage: 44.7 MB

(45462, 128)

In [5]:
df.describe()

,SEQN,SDDSRVYR,RIDSTATR,RIAGENDR,RIDAGEYR,RIDAGEMN,RIDRETH1,RIDRETH3,RIDEXMON,RIDEXAGY,...,DMDYRUSZ,DMDMARTZ,WTINTPRP,WTMECPRP,LBDHRPLC,WTSAFPRP,LBXNRBC,LBDSATLC,LBDSGTLC,LBDSTBLC
count,45462.000000,45462.000000,45462.000000,45462.000000,4.546200e+04,2.981000e+03,45462.000000,45462.000000,42995.000000,3418.000000,...,3028.000000,9232.000000,15560.000000,1.556000e+04,1.460000e+02,5.090000e+03,1.215100e+04,9.473000e+03,9.473000e+03,9.475000e+03
mean,91505.187035,27.856034,1.945735,1.505697,3.233067e+01,1.043844e+01,3.156856,3.372377,1.501012,9.641311,...,6.701453,1.708622,20714.921079,2.071492e+04,8.854274e+67,5.388396e+04,8.219900e-02,2.111264e-04,1.055632e-04,1.055409e-04
std,20068.910994,27.523884,0.226543,0.499973,2.486259e+01,7.008910e+00,1.263701,1.632560,0.500005,5.180846,...,18.534338,2.755878,25323.916482,2.711491e+04,7.538963e+68,6.853813e+04,9.228674e-02,1.452942e-02,1.027439e-02,1.027331e-02
min,62161.000000,7.000000,1.000000,1.000000,5.397605e-79,5.397605e-79,1.000000,1.000000,1.000000,2.000000,...,1.000000,1.000000,1017.784203,5.397605e-79,-2.938437e+56,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79
25%,75166.250000,8.000000,2.000000,1.000000,1.000000e+01,4.000000e+00,2.000000,2.000000,1.000000,5.000000,...,2.000000,1.000000,7435.543058,6.762822e+03,-2.938383e+56,1.730597e+04,5.397605e-79,5.397605e-79,5.397605e-79,5.397605e-79
50%,86531.500000,9.000000,2.000000,2.000000,2.800000e+01,9.000000e+00,3.000000,3.000000,2.000000,9.000000,...,3.000000,1.000000,12712.564300,1.263958e+04,-2.286424e-04,3.284510e+04,1.000000e-01,5.397605e-79,5.397605e-79,5.397605e-79
75%,113456.750000,66.000000,2.000000,2.000000,5.400000e+01,1.600000e+01,4.000000,4.000000,2.000000,14.000000,...,4.000000,2.000000,22761.140907,2.330839e+04,5.397605e-79,6.213588e+04,1.000000e-01,5.397605e-79,5.397605e-79,5.397605e-79
max,124822.000000,66.000000,2.000000,2.000000,8.000000e+01,2.400000e+01,5.000000,7.000000,2.000000,20.000000,...,99.000000,99.000000,338363.600192,3.675557e+05,6.463620e+69,7.412592e+05,3.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00

In [6]:
df.isna().mean().sort_values()

SEQN        0.000000
year        0.000000
SDMVSTRA    0.000000
SIAINTRP    0.000000
SIALANG     0.000000
              ...
LBDINSI     0.936628
LBXIN       0.936628
LBXHE2      0.938080
DMQADFC     0.964344
LBDHRPLC    0.996789
Length: 128, dtype: float64

In [7]:
df['RIDAGEYR'].sort_values()

7980     5.397605e-79
5276     5.397605e-79
27404    5.397605e-79
2835     5.397605e-79
18747    5.397605e-79
             ...
29402    8.000000e+01
971      8.000000e+01
7119     8.000000e+01
29640    8.000000e+01
42365    8.000000e+01
Name: RIDAGEYR, Length: 45462, dtype: float64

In [8]:
df.select_dtypes(include=["object", "string"]).columns

Index(['year'], dtype='str')

In [9]:
numeric_cols = df.select_dtypes(include="number").columns

df[numeric_cols] = df[numeric_cols].mask(
    df[numeric_cols].abs() < 1e-10
)

In [10]:
df["RIDAGEYR"].describe()

count    43695.000000
mean        33.638105
std         24.477865
min          1.000000
25%         11.000000
50%         30.000000
75%         55.000000
max         80.000000
Name: RIDAGEYR, dtype: float64

In [11]:
df.isna().mean().sort_values(ascending=False)

LBDSTBLC    0.999978
LBDSGTLC    0.999978
LBDSATLC    0.999956
LBDHRPLC    0.997470
DMQADFC     0.964344
              ...
SIALANG     0.000000
SIAINTRP    0.000000
year        0.000000
SDMVSTRA    0.000000
SEQN        0.000000
Length: 128, dtype: float64

In [12]:
df.columns

Index(['SEQN', 'SDDSRVYR', 'RIDSTATR', 'RIAGENDR', 'RIDAGEYR', 'RIDAGEMN',
       'RIDRETH1', 'RIDRETH3', 'RIDEXMON', 'RIDEXAGY',
       ...
       'DMDYRUSZ', 'DMDMARTZ', 'WTINTPRP', 'WTMECPRP', 'LBDHRPLC', 'WTSAFPRP',
       'LBXNRBC', 'LBDSATLC', 'LBDSGTLC', 'LBDSTBLC'],
      dtype='str', length=128)

In [16]:
all_cols = []
for a in df.columns:
    all_cols.append(a)

In [23]:
len(all_cols)

128

In [24]:
df.columns.tolist()

['SEQN',
 'SDDSRVYR',
 'RIDSTATR',
 'RIAGENDR',
 'RIDAGEYR',
 'RIDAGEMN',
 'RIDRETH1',
 'RIDRETH3',
 'RIDEXMON',
 'RIDEXAGY',
 'RIDEXAGM',
 'DMQMILIZ',
 'DMQADFC',
 'DMDBORN4',
 'DMDCITZN',
 'DMDYRSUS',
 'DMDEDUC3',
 'DMDEDUC2',
 'DMDMARTL',
 'RIDEXPRG',
 'SIALANG',
 'SIAPROXY',
 'SIAINTRP',
 'FIALANG',
 'FIAPROXY',
 'FIAINTRP',
 'MIALANG',
 'MIAPROXY',
 'MIAINTRP',
 'AIALANGA',
 'WTINT2YR',
 'WTMEC2YR',
 'SDMVPSU',
 'SDMVSTRA',
 'INDHHIN2',
 'INDFMIN2',
 'INDFMPIR',
 'DMDHHSIZ',
 'DMDFMSIZ',
 'DMDHHSZA',
 'DMDHHSZB',
 'DMDHHSZE',
 'DMDHRGND',
 'DMDHRAGE',
 'DMDHRBR4',
 'DMDHREDU',
 'DMDHRMAR',
 'DMDHSEDU',
 'year',
 'LBXSAL',
 'LBDSALSI',
 'LBXSATSI',
 'LBXSASSI',
 'LBXSAPSI',
 'LBXSBU',
 'LBDSBUSI',
 'LBXSCA',
 'LBDSCASI',
 'LBXSCK',
 'LBXSCH',
 'LBDSCHSI',
 'LBXSC3SI',
 'LBXSCR',
 'LBDSCRSI',
 'LBXSGTSI',
 'LBXSGL',
 'LBDSGLSI',
 'LBXSIR',
 'LBDSIRSI',
 'LBXSLDSI',
 'LBXSPH',
 'LBDSPHSI',
 'LBXSTB',
 'LBDSTBSI',
 'LBXSTP',
 'LBDSTPSI',
 'LBXSUA',
 'LBDSUASI',
 'LBXSNASI',
 'LBXSKSI',
 'LBXSCLSI',
 'LBXSOSSI',
 'LBXSGB',
 'LBDSGBSI',
 'LBXSTR',
 'LBDSTRSI',
 'LBXGH',
 'LBDHDD',
 'LBDHDDSI',
 'WTSAF2YR',
 'LBXGLU',
 'LBDGLUSI',
 'LBXIN',
 'LBDINSI',
 'PHAFSTHR',
 'PHAFSTMN',
 'LBXWBCSI',
 'LBXLYPCT',
 'LBXMOPCT',
 'LBXNEPCT',
 'LBXEOPCT',
 'LBXBAPCT',
 'LBDLYMNO',
 'LBDMONO',
 'LBDNENO',
 'LBDEONO',
 'LBDBANO',
 'LBXRBCSI',
 'LBXHGB',
 'LBXHCT',
 'LBXMCVSI',
 'LBXMCHSI',
 'LBXMC',
 'LBXRDW',
 'LBXPLTSI',
 'LBXMPSI',
 'LBXHE1',
 'LBXHE2',
 'DMDYRUSZ',
 'DMDMARTZ',
 'WTINTPRP',
 'WTMECPRP',
 'LBDHRPLC',
 'WTSAFPRP',
 'LBXNRBC',
 'LBDSATLC',
 'LBDSGTLC',
 'LBDSTBLC']