In [1]:
import pandas as pd
import seaborn as sns
from pathlib import Path

In [2]:
base_path = Path('/Users/anuj/Documents/CodeBase/Bioinformatics_projects/biological-age-prediction/data/raw')

In [3]:
data = {}
for years in base_path.iterdir():
    year = years.name
    
    for features in years.glob('*.xpt'):
        
        feature_name = features.stem.split("_")
        if feature_name[0] == 'P':
            feature_name = feature_name[1]
        else:
            feature_name = feature_name[0]
        
                           
        df = pd.read_sas(features, format='xport', encoding="latin1")
        
        df['year'] = year
        data[(year, feature_name)] = df

/var/folders/sl/clykmrq15rd0ksl37m6bnksw0000gn/T/ipykernel_87560/258438990.py:14: UserWarning: xport file may be corrupted.
  df = pd.read_sas(features, format='xport', encoding="latin1")

In [4]:
for key, value in data.items():
    print(f'key = {key} & value = {value.shape}')

key = ('2017-20', 'HSCRP') & value = (17047, 4)
key = ('2017-20', 'DEMO') & value = (15560, 30)
key = ('2017-20', 'GLU') & value = (5090, 5)
key = ('2017-20', 'CBC') & value = (13772, 23)
key = ('2017-20', 'HDL') & value = (12198, 4)
key = ('2017-20', 'BIOPRO') & value = (10409, 42)
key = ('2017-20', 'GHB') & value = (10409, 3)
key = ('2011-12', 'BIOPRO') & value = (6549, 39)
key = ('2011-12', 'GHB') & value = (6549, 3)
key = ('2011-12', 'DEMO') & value = (9756, 49)
key = ('2011-12', 'HDL') & value = (7821, 4)
key = ('2011-12', 'GLU') & value = (3239, 9)
key = ('2011-12', 'CBC') & value = (8956, 22)
key = ('2013-14', 'CBC') & value = (9422, 22)
key = ('2013-14', 'GLU') & value = (3329, 7)
key = ('2013-14', 'HDL') & value = (8291, 4)
key = ('2013-14', 'DEMO') & value = (10175, 48)
key = ('2013-14', 'GHB') & value = (6979, 3)
key = ('2013-14', 'BIOPRO') & value = (6979, 39)
key = ('2015-16', 'CBC') & value = (9165, 22)
key = ('2015-16', 'GLU') & value = (3191, 5)
key = ('2015-16', 'HSV') & value = (3710, 4)
key = ('2015-16', 'HDL') & value = (8021, 4)
key = ('2015-16', 'DEMO') & value = (9971, 48)
key = ('2015-16', 'GHB') & value = (6744, 3)
key = ('2015-16', 'BIOPRO') & value = (6744, 39)

### merge data - all_years, all_features

In [5]:
data[('2011-12', 'DEMO')]

,SEQN,SDDSRVYR,RIDSTATR,RIAGENDR,RIDAGEYR,RIDAGEMN,RIDRETH1,RIDRETH3,RIDEXMON,RIDEXAGY,...,DMDHHSZA,DMDHHSZB,DMDHHSZE,DMDHRGND,DMDHRAGE,DMDHRBR4,DMDHREDU,DMDHRMAR,DMDHSEDU,year
0,62161.0,7.0,2.0,1.0,22.0,NaN,3.0,3.0,2.0,NaN,...,5.397605e-79,1.000000e+00,5.397605e-79,2.0,50.0,1.0,5.0,1.0,5.0,2011-12
1,62162.0,7.0,2.0,2.0,3.0,NaN,1.0,1.0,1.0,3.0,...,2.000000e+00,2.000000e+00,5.397605e-79,2.0,24.0,1.0,3.0,6.0,NaN,2011-12
2,62163.0,7.0,2.0,1.0,14.0,NaN,5.0,6.0,2.0,14.0,...,5.397605e-79,2.000000e+00,1.000000e+00,1.0,42.0,1.0,5.0,1.0,4.0,2011-12
3,62164.0,7.0,2.0,2.0,44.0,NaN,3.0,3.0,1.0,NaN,...,1.000000e+00,2.000000e+00,5.397605e-79,1.0,52.0,1.0,4.0,1.0,4.0,2011-12
4,62165.0,7.0,2.0,2.0,14.0,NaN,4.0,4.0,2.0,14.0,...,1.000000e+00,2.000000e+00,5.397605e-79,2.0,33.0,2.0,2.0,77.0,NaN,2011-12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9751,71912.0,7.0,2.0,1.0,40.0,NaN,3.0,3.0,2.0,NaN,...,5.397605e-79,1.000000e+00,5.397605e-79,2.0,39.0,1.0,4.0,1.0,1.0,2011-12
9752,71913.0,7.0,2.0,2.0,18.0,NaN,5.0,6.0,1.0,18.0,...,5.397605e-79,2.000000e+00,1.000000e+00,1.0,61.0,1.0,4.0,1.0,5.0,2011-12
9753,71914.0,7.0,2.0,2.0,10.0,NaN,3.0,3.0,2.0,10.0,...,1.000000e+00,3.000000e+00,5.397605e-79,1.0,39.0,1.0,4.0,1.0,4.0,2011-12
9754,71915.0,7.0,2.0,1.0,60.0,NaN,3.0,3.0,2.0,NaN,...,5.397605e-79,5.397605e-79,1.000000e+00,1.0,60.0,1.0,5.0,5.0,NaN,2011-12
9755,71916.0,7.0,2.0,1.0,16.0,NaN,3.0,3.0,1.0,16.0,...,5.397605e-79,1.000000e+00,5.397605e-79,1.0,49.0,1.0,2.0,3.0,NaN,2011-12

## Combine yearly data
From each year, extract one feature eg. DEMO and add rest of the features on DSQN.

In [6]:
year = []

for years in data.keys():
    year.append(years[0])

all_years = list(set(year))
all_years

['2015-16', '2011-12', '2013-14', '2017-20']

### Get features list

In [7]:
features = []

for key in data.keys():
    features.append(key[1])
    
All_features = list(set(features))
All_features

['CBC', 'GHB', 'GLU', 'DEMO', 'BIOPRO', 'HDL', 'HSCRP', 'HSV']

### Merge year

In [8]:
merged_data = {}
for year in all_years:
    df_merged = data[(year,'DEMO')].copy()

    for feature in All_features:

        if feature == 'DEMO':
            continue

        if (year, feature) not in data:
            continue

        df_feature = data[(year, feature)]

        df_feature = df_feature.drop(columns=['year'], errors='ignore')

        df_merged = pd.merge(df_merged, df_feature, on = "SEQN", how = 'left')

        merged_data[year] = df_merged
        

df_merged

,SEQN,SDDSRVYR,RIDSTATR,RIAGENDR,RIDAGEYR,RIDAGEMN,RIDRETH1,RIDRETH3,RIDEXMON,DMDBORN4,...,LBXSTP,LBDSTPSI,LBXSTR,LBDSTRSI,LBXSUA,LBDSUASI,LBDHDD,LBDHDDSI,LBXHSCRP,LBDHRPLC
0,109263.0,66.0,2.0,1.0,2.0,NaN,5.0,6.0,2.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,109264.0,66.0,2.0,2.0,13.0,NaN,1.0,1.0,2.0,1.0,...,6.9,69.0,54.0,0.610,3.5,208.2,72.0,1.86,NaN,NaN
2,109265.0,66.0,2.0,1.0,2.0,NaN,3.0,3.0,2.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,109266.0,66.0,2.0,2.0,29.0,NaN,5.0,6.0,2.0,2.0,...,6.8,68.0,86.0,0.971,4.9,291.5,56.0,1.45,NaN,NaN
4,109267.0,66.0,1.0,2.0,21.0,NaN,2.0,2.0,NaN,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15555,124818.0,66.0,2.0,1.0,40.0,NaN,4.0,4.0,1.0,1.0,...,7.4,74.0,71.0,0.802,5.9,350.9,50.0,1.29,NaN,NaN
15556,124819.0,66.0,2.0,1.0,2.0,NaN,4.0,4.0,2.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15557,124820.0,66.0,2.0,2.0,7.0,NaN,3.0,3.0,2.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,64.0,1.66,NaN,NaN
15558,124821.0,66.0,2.0,1.0,63.0,NaN,4.0,4.0,1.0,1.0,...,6.7,67.0,52.0,0.587,6.0,356.9,44.0,1.14,NaN,NaN
15559,124822.0,66.0,2.0,1.0,74.0,NaN,2.0,2.0,2.0,2.0,...,6.9,69.0,77.0,0.869,5.6,333.1,65.0,1.68,NaN,NaN

In [9]:
print(merged_data['2015-16'].shape)
print(df_merged.shape)
print(merged_data.keys())
print(df_merged.columns[:20])

(9971, 113)
(15560, 99)
dict_keys(['2015-16', '2011-12', '2013-14', '2017-20'])
Index(['SEQN', 'SDDSRVYR', 'RIDSTATR', 'RIAGENDR', 'RIDAGEYR', 'RIDAGEMN',
       'RIDRETH1', 'RIDRETH3', 'RIDEXMON', 'DMDBORN4', 'DMDYRUSZ', 'DMDEDUC2',
       'DMDMARTZ', 'RIDEXPRG', 'SIALANG', 'SIAPROXY', 'SIAINTRP', 'FIALANG',
       'FIAPROXY', 'FIAINTRP'],
      dtype='str')

In [10]:
dfs = []

for year, df_year in merged_data.items():
    df_year['year'] = year
    dfs.append(df_year)


df = pd.concat(dfs, ignore_index=True)

In [11]:
df_merged.columns

Index(['SEQN', 'SDDSRVYR', 'RIDSTATR', 'RIAGENDR', 'RIDAGEYR', 'RIDAGEMN',
       'RIDRETH1', 'RIDRETH3', 'RIDEXMON', 'DMDBORN4', 'DMDYRUSZ', 'DMDEDUC2',
       'DMDMARTZ', 'RIDEXPRG', 'SIALANG', 'SIAPROXY', 'SIAINTRP', 'FIALANG',
       'FIAPROXY', 'FIAINTRP', 'MIALANG', 'MIAPROXY', 'MIAINTRP', 'AIALANGA',
       'WTINTPRP', 'WTMECPRP', 'SDMVPSU', 'SDMVSTRA', 'INDFMPIR', 'year',
       'LBXWBCSI', 'LBXLYPCT', 'LBXMOPCT', 'LBXNEPCT', 'LBXEOPCT', 'LBXBAPCT',
       'LBDLYMNO', 'LBDMONO', 'LBDNENO', 'LBDEONO', 'LBDBANO', 'LBXRBCSI',
       'LBXHGB', 'LBXHCT', 'LBXMCVSI', 'LBXMC', 'LBXMCHSI', 'LBXRDW',
       'LBXPLTSI', 'LBXMPSI', 'LBXNRBC', 'LBXGH', 'WTSAFPRP', 'LBXGLU',
       'LBDGLUSI', 'LBXSATSI', 'LBDSATLC', 'LBXSAL', 'LBDSALSI', 'LBXSAPSI',
       'LBXSASSI', 'LBXSC3SI', 'LBXSBU', 'LBDSBUSI', 'LBXSCLSI', 'LBXSCK',
       'LBXSCR', 'LBDSCRSI', 'LBXSGB', 'LBDSGBSI', 'LBXSGL', 'LBDSGLSI',
       'LBXSGTSI', 'LBDSGTLC', 'LBXSIR', 'LBDSIRSI', 'LBXSLDSI', 'LBXSOSSI',
       'LBXSPH', 'LBDSPHSI', 'LBXSKSI', 'LBXSNASI', 'LBXSTB', 'LBDSTBSI',
       'LBDSTBLC', 'LBXSCA', 'LBDSCASI', 'LBXSCH', 'LBDSCHSI', 'LBXSTP',
       'LBDSTPSI', 'LBXSTR', 'LBDSTRSI', 'LBXSUA', 'LBDSUASI', 'LBDHDD',
       'LBDHDDSI', 'LBXHSCRP', 'LBDHRPLC'],
      dtype='str')

In [12]:
df_merged.index

RangeIndex(start=0, stop=15560, step=1)

In [13]:
import sys
print(sys.path)
import os
print(os.getcwd())

['/Library/Frameworks/Python.framework/Versions/3.13/lib/python313.zip', '/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13', '/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/lib-dynload', '', '/Users/anuj/Documents/CodeBase/Bioinformatics_projects/biological-age-prediction/.venv/lib/python3.13/site-packages', '/Users/anuj/Documents/CodeBase/Bioinformatics_projects/biological-age-prediction/src']
/Users/anuj/Documents/CodeBase/Bioinformatics_projects/biological-age-prediction/notebooks